name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Source Cargo Environment
        run: source $HOME/.cargo/env

      - name: Ruff
        run: |
          uvx ruff check src
          uvx ruff format --check src

      - name: Run tests
        run: |
          uv run pytest tests -m 'not integration'
